server.port=8085
spring.application.name=telemetry-service

spring.profiles.active=dev

mqtt.broker.url=tcp://localhost:1883

# Elements take their values from maven pom.xml build-related information
documentation.application.description=@project.description@
documentation.application.version=@project.version@

# JWT Configuration Properties
authorization.jwt.secret=WriteHereYourSecretStringForTokenSigningCredentials
authorization.jwt.expiration.days=7

# CORS Configuration
spring.graphql.cors.allowed-origins=https://front-opensource.web.app
spring.graphql.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.graphql.cors.allowed-headers=Origin,Accept,X-Requested-With,Content-Type,Authorization,Access-Control-Request-Method,Access-Control-Request-Headers
spring.graphql.cors.allow-credentials=true
